In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("Cardetails.csv")
df.head()

name  year  selling_price  km_driven    fuel  \
0        Maruti Swift Dzire VDI  2014         450000     145500  Diesel   
1  Skoda Rapid 1.5 TDI Ambition  2014         370000     120000  Diesel   
2      Honda City 2017-2020 EXi  2006         158000     140000  Petrol   
3     Hyundai i20 Sportz Diesel  2010         225000     127000  Diesel   
4        Maruti Swift VXI BSIII  2007         130000     120000  Petrol   

  seller_type transmission         owner     mileage   engine   max_power  \
0  Individual       Manual   First Owner   23.4 kmpl  1248 CC      74 bhp   
1  Individual       Manual  Second Owner  21.14 kmpl  1498 CC  103.52 bhp   
2  Individual       Manual   Third Owner   17.7 kmpl  1497 CC      78 bhp   
3  Individual       Manual   First Owner   23.0 kmpl  1396 CC      90 bhp   
4  Individual       Manual   First Owner   16.1 kmpl  1298 CC    88.2 bhp   

                     torque  seats  
0            190Nm@ 2000rpm    5.0  
1       250Nm@ 1500-2500rpm    5.0  
2     12.7@ 2,700(kgm@ rpm)    5.0  
3  22.4 kgm at 1750-2750rpm    5.0  
4     11.5@ 4,500(kgm@ rpm)    5.0

In [3]:
df.shape

(8128, 13)

In [4]:
df.dropna(inplace=True) #all null value remove

In [5]:
df.shape

(7906, 13)

In [6]:
df.drop_duplicates(inplace=True) #reomve all duplicate value

In [7]:
df.shape

(6717, 13)

In [8]:
#we have data all is string so we use label encoder 

In [9]:
from sklearn.preprocessing import LabelEncoder

In [10]:
labelencoding  = LabelEncoder()

In [11]:
df.head(2)

name  year  selling_price  km_driven    fuel  \
0        Maruti Swift Dzire VDI  2014         450000     145500  Diesel   
1  Skoda Rapid 1.5 TDI Ambition  2014         370000     120000  Diesel   

  seller_type transmission         owner     mileage   engine   max_power  \
0  Individual       Manual   First Owner   23.4 kmpl  1248 CC      74 bhp   
1  Individual       Manual  Second Owner  21.14 kmpl  1498 CC  103.52 bhp   

                torque  seats  
0       190Nm@ 2000rpm    5.0  
1  250Nm@ 1500-2500rpm    5.0

In [12]:
df["name"].unique()

array(['Maruti Swift Dzire VDI', 'Skoda Rapid 1.5 TDI Ambition',
       'Honda City 2017-2020 EXi', ..., 'Tata Nexon 1.5 Revotorq XT',
       'Ford Freestyle Titanium Plus Diesel BSIV',
       'Toyota Innova 2.5 GX (Diesel) 8 Seater BS IV'], dtype=object)

In [13]:
# df["name"] = labelencoding.fit_transform(df["name"])

In [14]:
df.head(2)

name  year  selling_price  km_driven    fuel  \
0        Maruti Swift Dzire VDI  2014         450000     145500  Diesel   
1  Skoda Rapid 1.5 TDI Ambition  2014         370000     120000  Diesel   

  seller_type transmission         owner     mileage   engine   max_power  \
0  Individual       Manual   First Owner   23.4 kmpl  1248 CC      74 bhp   
1  Individual       Manual  Second Owner  21.14 kmpl  1498 CC  103.52 bhp   

                torque  seats  
0       190Nm@ 2000rpm    5.0  
1  250Nm@ 1500-2500rpm    5.0

In [15]:
def car_gr(df):
    df = df.split(" ")[0]
    return df.strip(" ")


In [16]:
df["name"]=df["name"].apply(car_gr)

In [17]:
df["name"].unique()

array(['Maruti', 'Skoda', 'Honda', 'Hyundai', 'Toyota', 'Ford', 'Renault',
       'Mahindra', 'Tata', 'Chevrolet', 'Datsun', 'Jeep', 'Mercedes-Benz',
       'Mitsubishi', 'Audi', 'Volkswagen', 'BMW', 'Nissan', 'Lexus',
       'Jaguar', 'Land', 'MG', 'Volvo', 'Daewoo', 'Kia', 'Fiat', 'Force',
       'Ambassador', 'Ashok', 'Isuzu', 'Opel'], dtype=object)

In [18]:
df["name"]=labelencoding.fit_transform(df["name"])

In [19]:
df["name"].unique()

array([20, 26, 10, 11, 28,  9, 25, 19, 27,  4,  6, 14, 21, 22,  2, 29,  3,
       23, 17, 13, 16, 18, 30,  5, 15,  7,  8,  0,  1, 12, 24])

In [20]:
df.head()

name  year  selling_price  km_driven    fuel seller_type transmission  \
0    20  2014         450000     145500  Diesel  Individual       Manual   
1    26  2014         370000     120000  Diesel  Individual       Manual   
2    10  2006         158000     140000  Petrol  Individual       Manual   
3    11  2010         225000     127000  Diesel  Individual       Manual   
4    20  2007         130000     120000  Petrol  Individual       Manual   

          owner     mileage   engine   max_power                    torque  \
0   First Owner   23.4 kmpl  1248 CC      74 bhp            190Nm@ 2000rpm   
1  Second Owner  21.14 kmpl  1498 CC  103.52 bhp       250Nm@ 1500-2500rpm   
2   Third Owner   17.7 kmpl  1497 CC      78 bhp     12.7@ 2,700(kgm@ rpm)   
3   First Owner   23.0 kmpl  1396 CC      90 bhp  22.4 kgm at 1750-2750rpm   
4   First Owner   16.1 kmpl  1298 CC    88.2 bhp     11.5@ 4,500(kgm@ rpm)   

   seats  
0    5.0  
1    5.0  
2    5.0  
3    5.0  
4    5.0

In [21]:
df["fuel"].unique()

array(['Diesel', 'Petrol', 'LPG', 'CNG'], dtype=object)

In [22]:
df["fuel"] =labelencoding.fit_transform(df["fuel"])
df["fuel"].unique()

array([1, 3, 2, 0])

In [23]:
df["seller_type"].unique()

array(['Individual', 'Dealer', 'Trustmark Dealer'], dtype=object)

In [24]:
df["seller_type"]=labelencoding.fit_transform(df["seller_type"])
df["seller_type"].unique()

array([1, 0, 2])

In [25]:
df["transmission"].unique()

array(['Manual', 'Automatic'], dtype=object)

In [26]:
df["transmission"]=labelencoding.fit_transform(df["transmission"])
df["transmission"].unique()

array([1, 0])

In [27]:
df["owner"].unique()

array(['First Owner', 'Second Owner', 'Third Owner',
       'Fourth & Above Owner', 'Test Drive Car'], dtype=object)

In [28]:
df["owner"] = labelencoding.fit_transform(df["owner"])
df["owner"].unique()

array([0, 2, 4, 1, 3])

In [29]:
df["mileage"].unique()

array(['23.4 kmpl', '21.14 kmpl', '17.7 kmpl', '23.0 kmpl', '16.1 kmpl',
       '20.14 kmpl', '17.3 km/kg', '23.59 kmpl', '20.0 kmpl',
       '19.01 kmpl', '17.3 kmpl', '19.3 kmpl', '18.9 kmpl', '18.15 kmpl',
       '24.52 kmpl', '19.7 kmpl', '22.54 kmpl', '21.0 kmpl', '25.5 kmpl',
       '26.59 kmpl', '21.5 kmpl', '20.3 kmpl', '21.4 kmpl', '24.7 kmpl',
       '18.2 kmpl', '16.8 kmpl', '24.3 kmpl', '14.0 kmpl', '18.6 kmpl',
       '33.44 km/kg', '23.95 kmpl', '17.0 kmpl', '20.63 kmpl',
       '13.93 kmpl', '16.0 kmpl', '17.8 kmpl', '18.5 kmpl', '12.55 kmpl',
       '12.99 kmpl', '14.8 kmpl', '13.5 kmpl', '26.0 kmpl', '20.65 kmpl',
       '27.3 kmpl', '11.36 kmpl', '17.68 kmpl', '14.28 kmpl',
       '18.53 kmpl', '14.84 kmpl', '21.12 kmpl', '20.36 kmpl',
       '21.27 kmpl', '18.16 kmpl', '22.0 kmpl', '25.1 kmpl', '20.51 kmpl',
       '21.66 kmpl', '25.2 kmpl', '22.9 kmpl', '16.02 kmpl', '20.54 kmpl',
       '22.77 kmpl', '15.71 kmpl', '23.1 kmpl', '19.02 kmpl',
       '19.81 kmpl', '26

In [30]:
def car_g(df):
    df = df.split(" ")[0]
    return df.strip(" ")

In [31]:
df["mileage"]=df["mileage"].apply(car_g)

In [32]:
df["mileage"].unique()

array(['23.4', '21.14', '17.7', '23.0', '16.1', '20.14', '17.3', '23.59',
       '20.0', '19.01', '19.3', '18.9', '18.15', '24.52', '19.7', '22.54',
       '21.0', '25.5', '26.59', '21.5', '20.3', '21.4', '24.7', '18.2',
       '16.8', '24.3', '14.0', '18.6', '33.44', '23.95', '17.0', '20.63',
       '13.93', '16.0', '17.8', '18.5', '12.55', '12.99', '14.8', '13.5',
       '26.0', '20.65', '27.3', '11.36', '17.68', '14.28', '18.53',
       '14.84', '21.12', '20.36', '21.27', '18.16', '22.0', '25.1',
       '20.51', '21.66', '25.2', '22.9', '16.02', '20.54', '22.77',
       '15.71', '23.1', '19.02', '19.81', '26.2', '16.47', '15.04',
       '19.1', '21.79', '18.8', '21.21', '15.37', '11.79', '19.0', '14.3',
       '15.8', '15.1', '19.09', '22.32', '21.9', '14.53', '21.63',
       '20.85', '20.45', '19.67', '23.01', '20.77', '17.92', '17.01',
       '22.37', '19.33', '9.5', '12.83', '22.48', '16.78', '14.67',
       '15.0', '13.96', '18.0', '12.07', '26.21', '10.8', '16.3', '13.6',
     

In [33]:
df.head(2)

name  year  selling_price  km_driven  fuel  seller_type  transmission  \
0    20  2014         450000     145500     1            1             1   
1    26  2014         370000     120000     1            1             1   

   owner mileage   engine   max_power               torque  seats  
0      0    23.4  1248 CC      74 bhp       190Nm@ 2000rpm    5.0  
1      2   21.14  1498 CC  103.52 bhp  250Nm@ 1500-2500rpm    5.0

In [34]:
df["engine"].unique()

array(['1248 CC', '1498 CC', '1497 CC', '1396 CC', '1298 CC', '1197 CC',
       '1061 CC', '796 CC', '1364 CC', '1399 CC', '1461 CC', '993 CC',
       '1198 CC', '1199 CC', '998 CC', '1591 CC', '2179 CC', '1368 CC',
       '2982 CC', '2494 CC', '2143 CC', '2477 CC', '1462 CC', '2755 CC',
       '1968 CC', '1798 CC', '1196 CC', '1373 CC', '1598 CC', '1998 CC',
       '1086 CC', '1194 CC', '1172 CC', '1405 CC', '1582 CC', '999 CC',
       '2487 CC', '1999 CC', '3604 CC', '2987 CC', '1995 CC', '1451 CC',
       '1969 CC', '2967 CC', '2497 CC', '1797 CC', '1991 CC', '2362 CC',
       '1493 CC', '1599 CC', '1341 CC', '1794 CC', '799 CC', '1193 CC',
       '2696 CC', '1495 CC', '1186 CC', '1047 CC', '2498 CC', '2956 CC',
       '2523 CC', '1120 CC', '624 CC', '1496 CC', '1984 CC', '2354 CC',
       '814 CC', '793 CC', '1799 CC', '936 CC', '1956 CC', '1997 CC',
       '1499 CC', '1948 CC', '2997 CC', '2489 CC', '2499 CC', '2609 CC',
       '2953 CC', '1150 CC', '1994 CC', '1388 CC', '1527 CC'

In [35]:
df["engine"]=df["engine"].apply(car_g)

In [37]:
df["engine"].unique()

array(['1248', '1498', '1497', '1396', '1298', '1197', '1061', '796',
       '1364', '1399', '1461', '993', '1198', '1199', '998', '1591',
       '2179', '1368', '2982', '2494', '2143', '2477', '1462', '2755',
       '1968', '1798', '1196', '1373', '1598', '1998', '1086', '1194',
       '1172', '1405', '1582', '999', '2487', '1999', '3604', '2987',
       '1995', '1451', '1969', '2967', '2497', '1797', '1991', '2362',
       '1493', '1599', '1341', '1794', '799', '1193', '2696', '1495',
       '1186', '1047', '2498', '2956', '2523', '1120', '624', '1496',
       '1984', '2354', '814', '793', '1799', '936', '1956', '1997',
       '1499', '1948', '2997', '2489', '2499', '2609', '2953', '1150',
       '1994', '1388', '1527', '2199', '995', '2993', '1586', '1390',
       '909', '2393', '3198', '1339', '2835', '2092', '1595', '2496',
       '1596', '1597', '2596', '2148', '1299', '1590', '2231', '2694',
       '2200', '1795', '1896', '1796', '1422', '1489', '2359', '2197',
       '2999', '1

In [38]:
df["max_power"].unique()

array(['74 bhp', '103.52 bhp', '78 bhp', '90 bhp', '88.2 bhp',
       '81.86 bhp', '57.5 bhp', '37 bhp', '67.1 bhp', '68.1 bhp',
       '108.45 bhp', '60 bhp', '73.9 bhp', '67 bhp', '82 bhp', '88.5 bhp',
       '46.3 bhp', '88.73 bhp', '64.1 bhp', '98.6 bhp', '88.8 bhp',
       '83.81 bhp', '83.1 bhp', '47.3 bhp', '73.8 bhp', '34.2 bhp',
       '35 bhp', '81.83 bhp', '40.3 bhp', '121.3 bhp', '138.03 bhp',
       '160.77 bhp', '117.3 bhp', '116.3 bhp', '83.14 bhp', '67.05 bhp',
       '168.5 bhp', '100 bhp', '120.7 bhp', '98.63 bhp', '175.56 bhp',
       '103.25 bhp', '171.5 bhp', '100.6 bhp', '174.33 bhp', '187.74 bhp',
       '170 bhp', '78.9 bhp', '88.76 bhp', '86.8 bhp', '108.495 bhp',
       '108.62 bhp', '93.7 bhp', '103.6 bhp', '98.59 bhp', '189 bhp',
       '67.04 bhp', '68.05 bhp', '58.2 bhp', '82.85 bhp', '81.80 bhp',
       '73 bhp', '120 bhp', '94.68 bhp', '160 bhp', '65 bhp', '155 bhp',
       '69.01 bhp', '126.32 bhp', '138.1 bhp', '83.8 bhp', '126.2 bhp',
       '98.96 bh

In [40]:
df["max_power"]=df["max_power"].apply(car_g)
df["max_power"].unique()

array(['74', '103.52', '78', '90', '88.2', '81.86', '57.5', '37', '67.1',
       '68.1', '108.45', '60', '73.9', '67', '82', '88.5', '46.3',
       '88.73', '64.1', '98.6', '88.8', '83.81', '83.1', '47.3', '73.8',
       '34.2', '35', '81.83', '40.3', '121.3', '138.03', '160.77',
       '117.3', '116.3', '83.14', '67.05', '168.5', '100', '120.7',
       '98.63', '175.56', '103.25', '171.5', '100.6', '174.33', '187.74',
       '170', '78.9', '88.76', '86.8', '108.495', '108.62', '93.7',
       '103.6', '98.59', '189', '67.04', '68.05', '58.2', '82.85',
       '81.80', '73', '120', '94.68', '160', '65', '155', '69.01',
       '126.32', '138.1', '83.8', '126.2', '98.96', '62.1', '86.7', '188',
       '214.56', '177', '280', '148.31', '254.79', '190', '177.46', '204',
       '141', '117.6', '241.4', '282', '150', '147.5', '108.5', '103.5',
       '183', '181.04', '157.7', '164.7', '91.1', '400', '68', '75',
       '85.8', '87.2', '53', '118', '103.2', '83', '84', '58.16',
       '147.94', 

In [41]:
df.head(1)

name  year  selling_price  km_driven  fuel  seller_type  transmission  \
0    20  2014         450000     145500     1            1             1   

   owner mileage engine max_power          torque  seats  
0      0    23.4   1248        74  190Nm@ 2000rpm    5.0

In [45]:
df.drop(["torque"],axis=1,inplace=True)

In [46]:
df.head(2)

name  year  selling_price  km_driven  fuel  seller_type  transmission  \
0    20  2014         450000     145500     1            1             1   
1    26  2014         370000     120000     1            1             1   

   owner mileage engine max_power  seats  
0      0    23.4   1248        74    5.0  
1      2   21.14   1498    103.52    5.0

In [48]:
df.shape

(6717, 12)

In [49]:
x=df.drop(["selling_price"],axis=1)

In [50]:
x

name  year  km_driven  fuel  seller_type  transmission  owner mileage  \
0       20  2014     145500     1            1             1      0    23.4   
1       26  2014     120000     1            1             1      2   21.14   
2       10  2006     140000     3            1             1      4    17.7   
3       11  2010     127000     1            1             1      0    23.0   
4       20  2007     120000     3            1             1      0    16.1   
...    ...   ...        ...   ...          ...           ...    ...     ...   
8121    20  2013      50000     3            1             1      2    18.9   
8122    11  2014      80000     1            1             1      2   22.54   
8123    11  2013     110000     3            1             1      0    18.5   
8124    11  2007     119000     1            1             1      1    16.8   
8125    20  2009     120000     1            1             1      0    19.3   

     engine max_power  seats  
0      1248        74    5.0  
1      1498    103.52    5.0  
2      1497        78    5.0  
3      1396        90    5.0  
4      1298      88.2    5.0  
...     ...       ...    ...  
8121    998      67.1    5.0  
8122   1396     88.73    5.0  
8123   1197     82.85    5.0  
8124   1493       110    5.0  
8125   1248      73.9    5.0  

[6717 rows x 11 columns]

In [51]:
y=df["selling_price"]

In [52]:
y

0       450000
1       370000
2       158000
3       225000
4       130000
         ...  
8121    260000
8122    475000
8123    320000
8124    135000
8125    382000
Name: selling_price, Length: 6717, dtype: int64

In [53]:
from sklearn.model_selection import train_test_split

In [55]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [60]:
x_train.shape

(5373, 11)

In [61]:
x_test.shape

(1344, 11)

In [57]:
from sklearn.linear_model import LinearRegression

In [59]:
model = LinearRegression()

In [62]:
model.fit(x_train,y_train)

LinearRegression()

In [65]:
model.score(x_test,y_test)

0.6180981876683789

In [66]:
p=model.predict(x_test)

In [68]:
p

np.float64(187069.4690426737)

In [73]:
input_data_model =pd.DataFrame([[26,2014,120000,1,1,1,2,21.14,1498,103.52,5.0]],
                columns=["name","year","km_driven","fuel","seller_type","transmission","owner","mileage","engine","max_power","seats"])

In [74]:
model.predict(input_data_model)

array([621083.89177883])

In [64]:
df.head(2)

name  year  selling_price  km_driven  fuel  seller_type  transmission  \
0    20  2014         450000     145500     1            1             1   
1    26  2014         370000     120000     1            1             1   

   owner mileage engine max_power  seats  
0      0    23.4   1248        74    5.0  
1      2   21.14   1498    103.52    5.0